title: ""
email: "jdezoort@princeton.edu"
description: >- # this means to ignore newlines until "baseurl:"
  Gage DeZoort's research webpage. 
twitter_username: gdezoort
github_username: gagedezoort
minimal_mistakes_skin: "mint"
# theme_color: "#4A90E2"
# theme_color_alt: "#7A42F4"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Gage DeZoort"
  avatar : "/assets/images/headshot.jpg"
  bio    : >-
    My name is Gage.
    I have a Ph.D. in particle physics and am now working at the intersection of ML and physics.
    In addition to my research, I am passionate about health/fitness, music (prog preferred),
    reading (fantasy/sci-fi), and teaching.
  location: "Princeton, NJ"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jdezoort@princeton.edu"
    - label: "CV"
      icon": "far fa-fw fa-file-pdf"
      url: "/assets/dezoort-cv-winter2025.pdf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GageDeZoort"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/GDezoort"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/gagedezoort/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GageDeZoort"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/GDezoort"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/gagedezoort/"
    - label: "Substack"
      icon: "bi bi-substack"
      url: "https://substack.com/@gagedezoort"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

assets:
  css:
    - /assets/css/custom.css

analytics:
  provider: "google"
  google:
    tracking_id: "G-QRVNXDMWV9"
    anonymize_ip: true