title: Gage DeZoort
description: ' '
author: "Gage DeZoort"

theme: minima

domain: gagedezoort.github.io
url: https://gagedezoort.github.io
base_url: /gagedezoort.github.io/

# Minima social links
twitter_username: gdezoort
github_username: gagedezoort
linkedin_username: gagedezoort

# Minima: show excerpts in the frontpage
show_excerpts: false

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/cv.md
  - _pages/papers.md
  - _includes/google24f6fa54d5562e9c.html

include:
    - _pages
    
exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - _posts